apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-ci-app
  namespace: cicd-lab

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sample-ci-app

  template:
    metadata:
      labels:
        app: sample-ci-app

    spec:

      containers:
        - name: sample-ci-app
          image: 510869689558.dkr.ecr.ap-southeast-2.amazonaws.com/sample-ci-app:27
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
