apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-ci-app
  namespace: cicd-lab

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sample-ci-app

  template:
    metadata:
      labels:
        app: sample-ci-app

    spec:
      imagePullSecrets:
        - name: ecr-pull-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload-priority
                    operator: In
                    values:
                      - primary
                      - secondary

          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: workload-priority
                    operator: In
                    values:
                      - primary

      containers:
        - name: sample-ci-app
          image: 510869689558.dkr.ecr.ap-southeast-2.amazonaws.com/sample-ci-app:39
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
              ephemeral-storage: "100Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
              ephemeral-storage: "500Mi"
